# RuboCop configuration for flowable gem
# https://docs.rubocop.org/rubocop/

plugins:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - '*.gem'
    - 'pkg/**/*'

# ============================================
# Layout
# ============================================

Layout/LineLength:
  Max: 120
  Exclude:
    - 'test/**/*'
    - '*.gemspec'
    - 'lib/flowable/flowable.rb'

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

# ============================================
# Metrics
# ============================================

Metrics/ClassLength:
  Max: 300
  Exclude:
    - 'test/**/*'
    - 'bin/*'

Metrics/ModuleLength:
  Max: 300
  Exclude:
    - 'test/**/*'

Metrics/MethodLength:
  Max: 30
  Exclude:
    - 'test/**/*'
    - 'bin/*'
    - 'examples/*'

Metrics/AbcSize:
  Max: 40
  Exclude:
    - 'test/**/*'
    - 'bin/*'
    - 'examples/*'

Metrics/CyclomaticComplexity:
  Max: 15
  Exclude:
    - 'bin/*'

Metrics/PerceivedComplexity:
  Max: 15
  Exclude:
    - 'bin/*'

Metrics/BlockLength:
  Exclude:
    - 'test/**/*'
    - 'Rakefile'
    - '*.gemspec'

Metrics/ParameterLists:
  Max: 8
  CountKeywordArgs: false

# ============================================
# Naming
# ============================================

Naming/PredicatePrefix:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Naming/MethodParameterName:
  AllowedNames:
    - id
    - to
    - at
    - by
    - on
    - in
    - io

# ============================================
# Style
# ============================================

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Style/StringLiterals:
  EnforcedStyle: single_quotes
  ConsistentQuotesInMultiline: true

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: no_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: no_comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: no_comma

Style/HashSyntax:
  EnforcedStyle: ruby19
  EnforcedShorthandSyntax: either

Style/SymbolArray:
  EnforcedStyle: percent

Style/WordArray:
  EnforcedStyle: percent

Style/RegexpLiteral:
  EnforcedStyle: mixed

Style/IfUnlessModifier:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/AccessorGrouping:
  EnforcedStyle: separated

Style/RedundantReturn:
  AllowMultipleReturnValues: true

Style/OptionalBooleanParameter:
  Enabled: false

Style/KeywordParametersOrder:
  Enabled: false

Style/OpenStructUse:
  Enabled: false

# ============================================
# Lint
# ============================================

Lint/MissingSuper:
  Enabled: false

Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true

# ============================================
# Security
# ============================================

Security/Open:
  Enabled: true

# ============================================
# Minitest
# ============================================

Minitest/MultipleAssertions:
  Max: 15

Minitest/AssertEmptyLiteral:
  Enabled: true

Minitest/TestFileName:
  Exclude:
    - 'test/integration/integration_test_helper.rb'
